# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0002_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(),
        ),
    ]
